### ISSUE TITLE
SBT build failure

### ISSUE THREAD

**Issue by tomasherman** [adept-dm/adept#18]
When i try to run sbt in the adept repo, i get the following error:

java.lang.IllegalArgumentException: Illegal pattern character 'Y'
    at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:768)
    at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:575)
    at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:500)
    at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:475)
    at AdeptBuild$$anonfun$3.apply(Build.scala:11)
    at AdeptBuild$$anonfun$3.apply(Build.scala:10)
    at sbt.Init$Value$$anonfun$apply$6.apply(Settings.scala:329)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:158)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:158)
    at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:177)
    at sbt.EvaluateSettings$INode.evaluate(INode.scala:132)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:64)
    at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:73)
    at sbt.EvaluateSettings$$anon$3.run(INode.scala:69)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:662)

**Comment by tomasherman** [comment]
i suck at github :/ sorry, closing this, check out the pull request please

**Comment by freekh** [comment]
Hehe.. no worries checcking it out now!
